### ISSUE TITLE
[r] [bug] `SOMAExperimentAxisQuery` `$X()` `$obs()` and `$var()` should  have an argument `iterated`

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/TileDB-SOMA#1271] opened 2023-04-21 18:37 UTC
**Describe the bug**
[r] [bug] [`SOMAExperimentAxisQuery`](https://github.com/single-cell-data/TileDB-SOMA/blob/02e0b2f9d7f728bfef7ee8d2e2df326f53c871f8/apis/r/R/SOMAExperimentAxisQuery.R#L28) `$X()` `$obs()` and `$var()` should  have an argument `iterated` hat gets passed to `read_arrow_table`

Otherwise there are no  low-latency reading capabilities o those methods from an Experiment Query.

**Comment by johnkerl** [comment] 2023-05-22 16:49
Duplicate of #1285

**Closed by johnkerl** 2023-05-22 16:49 UTC
Labels: bug, r-api, 1.0rc-r
