### ISSUE TITLE
[Issue] TileDB dictionary encoding, and empty strings in enumerations

### ISSUE THREAD

**Issue by mdylan2** [single-cell-data/TileDB-SOMA#2822] opened 2024-07-31 21:22 UTC
**Describe the bug**
I'm having an issue with appending an AnnData to a SOMA Experiment where a column in the Anndata obs has empty strings and I specify the tiledb Dictionary Encoding for the attribute in the obs Soma Dataframe.

**To Reproduce**
My working gist is here: https://gist.github.com/mdylan2/4ec7840e50a3a22a4b1cb6eb4a17c809.

Starting with the code above, and then uncommenting the platform config as below:
```
diff --git a/file.py b/file_2.py
index b8f815b..c69ded2 100644
--- a/file.py
+++ b/file_2.py
@@ -75,7 +75,7 @@ experiment.add_new_dataframe(
     "obs",
     schema=obs_schema,
     index_column_names=list(dict_['PAI_OBS_INDEX_COLUMNS'].keys()),
-    # platform_config=platform_config_obs
+    platform_config=platform_config_obs
 )
 # create `ms`
 measurements = experiment.add_new_collection("ms")
(END)
```

gives me the following error:
```
SOMAError: [TileDB::Filter] Error: CompressionFilter error; Dictionary encoding only applies to variable length strings
```

Why is the error happening? I suspect it's to do with the empty string but I'm unsure. If that is the case, how do I append this AnnData successfully, assuming that future AnnDatas will have the attribute filled out.

In addition, what should I be filling empty values with for in my AnnData before ingesting into soma? Eg: `pa.Dictionary`, `pa.bool_`, `pa.int64`?

**Versions (please complete the following information):**
 - TileDB-SOMA version: 1.12.3
 - Language and language version (e.g. Python 3.8, R 4.2.2): 3.10
 - OS (e.g. MacOS, Ubuntu Linux): Ubuntu

**Additional context**

**Comment by johnkerl** [comment] 2024-08-01 18:34
Hi @mdylan2!

There are two issues here:

* The error `Dictionary encoding only applies to variable length strings`
* How to indicate empty values in an enumerated type?

# First question

For the first one: perhaps we can improve the error message in TileDB Core, but the statement is correct: dictionary filters are supported on string columns. The `sample_name` column here isn't a string column -- it's a categorical/enumeration column. An enumeration, in turn, is really just an _int_ column (with various choices for index type, including int16, int32, etc.) accompanied by a separate enumeration table which is indexed by those ints. For example, if you have a one-million-sample column `color` which is an enumeration-of-string with values `"red", "yellow", "green"`, then what you have are one million values selected from among 0,1,2 down that column -- accompanied by (in the schema) a side table mapping 0 to "red", 1 to "yellow", and 2 to "green".  [I'm glossing over the distinction between ordered and unordered enums, for simplicity.)

Differences between string column with dictionary filter on storage, and enumeration-of-string column:

* String column with dictionary filter on storage:
  * On disk, values like 0,1,2 are stored in bulk (however thousands/millions), along with, on storage, a little lookup table mapping say 0 to "green", 1 to "red", 2 to "yellow"
  * You can apply other filters too: e.g. compressing that long list of 0,1,2
  * This is a storage-only thing: as soon as that column of the array is read into memory, it becomes an array of strings: thousands/millions/etc of "red", "yellow", "green".
* enumeration-of-string column:
  * On disk, values like 0,1,2 are stored in bulk (however thousands/millions), along with, on storage, a little lookup table mapping say 0 to "red", 1 to "yellow", 2 to "green" -- at the storage level, not too different from a dictionary filter
  * But thing is _not_ just a storage-only thing: as soon as that column of the array is read into memory, it is _still_ an enumeration: thousands/millions of values selected from 0,1,2, accompanied by a little lookup table mapping say 0 to "red", 1 to "yellow", 2 to "green"
  * Users get this -- in R, these are factors; in Python, they become Arrow categoricals, or Pandas categoricals, etc.

TileDB has had dictionary filters for a long time; enumerations are newer (as of last year). Enumerated types are a "level up" in that they offer some of the benefits of on-storage dictionary filters, while also offering high-fidelity round-tripping between TileDB enumerations, Arrow/Pandas categoricals, R factors, etc.

The on-storage filters available for your use when you have an enumeration column are the ones acceptable for int columns -- since the bulk data is int-only.

# Second question

Once I run your script without attempting to set a dictionary filter for the `sample_name` enumeration column, I find:

* `adata.obs["sample_name"] = " "` (space) works OK
* `adata.obs["sample_name"] = ""` (empty string) should work, but results in `Unable to extend an enumeration without a data buffer` at write time
* `adata.obs["sample_name"] = None` should work, and results in no error at write time, but results in `pyarrow.lib.ArrowIndexError: Index 0 out of bounds` at read time.

The latter two are TileDB-SOMA bugs which we'll fix.

**Comment by mdylan2** [comment] 2024-08-01 18:47
Awesome, thanks!

For other data types, eg: pa.int32 or pa.bool_, what should we fill N/A values with before ingesting using tiledbsoma.io.from_anndata()?

Would that be None or "" or " " as well?

**Comment by johnkerl** [comment] 2024-08-01 18:53
@mdylan2 I expect Python `None`.

I've assigned this task to myself for follow-up. We've had several PRs involving this, e.g. #248, #29, #1265, #1568, and #1834. We have had bugfixes and we do have unit-test coverage in place -- however, I'll need to do a more thorough audit, as we've found above a case we missed on those previous PRs.

**Comment by mdylan2** [comment] 2024-08-06 16:24
Having trouble with booleans, specifically regarding Pandas-Arrow compatibility. Adapting the gist above to add a boolean attribute:
```
+++ b/working append    
@@ -5,6 +5,7 @@ import os
 import scanpy as sc
 import tiledbsoma.io
 
+print("HERE")
 human_global_config = """
 # Columns and data types
 PAI_OBS_INDEX_COLUMNS: &PAI_OBS_INDEX_COLUMNS
@@ -13,6 +14,7 @@ PAI_OBS_INDEX_COLUMNS: &PAI_OBS_INDEX_COLUMNS
 PAI_OBS_CELL_COLUMNS: &PAI_OBS_CELL_COLUMNS
     barcode: large_string
     sample_name: categorical__large_string
+    is_cell: bool_
 
 PAI_OBS_TERM_COLUMNS:
     <<: *PAI_OBS_INDEX_COLUMNS
@@ -102,6 +104,11 @@ adata = sc.datasets.pbmc3k()
 adata.obs["barcode"] = adata.obs.index
 adata.obs["sample_name"] = " "
 adata.obs["sample_name"] = adata.obs["sample_name"].astype("category")
+
+# Nullable boolean: https://stackoverflow.com/questions/67402394/is-there-a-nullable-boolean-type-i-can-use-in-a-pandas-dataframe
+adata.obs["is_cell"] = None
+adata.obs["is_cell"] = adata.obs["is_cell"].astype("boolean")
+
 adata.var["gene"] = adata.var.index
 adata.layers["row_raw"] = adata.X
 adata.layers["row_norm"] = adata.X
 ```
 
 I get the following error:
 ```
  File "/Users/dylanmendonca/tiledb_debugging/4ec7840e50a3a22a4b1cb6eb4a17c809/venv/lib/python3.11/site-packages/tiledbsoma/_dataframe.py", line 473, in write
    values = _util.cast_values_to_target_schema(values, self.schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dylanmendonca/tiledb_debugging/4ec7840e50a3a22a4b1cb6eb4a17c809/venv/lib/python3.11/site-packages/tiledbsoma/_util.py", line 356, in cast_values_to_target_schema
    return values.cast(pa.schema(target_schema, values.schema.metadata))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3611, in pyarrow.lib.Table.cast
ValueError: Casting field 'is_cell' with null values to non-nullable
```

**Comment by eddelbuettel** [comment] 2024-08-06 17:25
Based on earlier explorations, you also cannot (easily) do NA or NULL in R's factors.  Missingness in factor variables just leads to them missing.

```r
> fct <- factor(c("red", "green", "blue", NA))
> set.seed(123)  # reproducible
> var <- sample(fct, 1000, replace=TRUE)
> table(var)
var
 blue green   red 
  257   248   249 
> 
```

So when a factor element is NA it is simply skipped. Sampling 1k elements leads to (here) 750ish because the forth is skipped.   And one _could_ have empty string as a lable but it is not quite what one wants

```r> fct <- factor(c("red", "green", "blue", ""))
> set.seed(123)  # reproducible
> var <- sample(fct, 1000, replace=TRUE)
> table(var)
var
       blue green   red 
  246   257   248   249 
> 
```

So no '' is a valid label.  Hm.  I am not quite sure what to make of it (and that is one of the reasons I didn't chime in earlier).

**Comment by johnkerl** [comment] 2024-08-06 17:55
@eddelbuettel thanks! Given this is a Python issue, I'll deep-dive it ...

**Comment by eddelbuettel** [comment] 2024-08-06 17:59
@johnkerl Likely worth some similar small-scale explorations but I would suspect the behavior to be similar.

**Comment by johnkerl** [comment] 2024-08-07 20:15
Hi @mdylan2 -- I have some (currently Python-only, R to come) experiments in my sandbox and I can tell you so far there are a few things going on.

* One issue is nullability of categorical columns within TileDB schemas. These are created from Arrow schemas.
  * TileDB core enumerated types support nullability (cc @davisp); the only question is under what circumstances do the TileDB categorical attributes created by TileDB-SOMA indeed have their core nullability flags set
  * In `tiledbsoma.Experiment.add_new_dataframe` you bring your own Arrow schema
    * Given your example path above, this leads to a TileDB Core schema with non-nullable category
    * A TileDB-SOMA bug: if you've got `None` in your input data then either we need to set the nullability flag in the TileDB schema, or, we need to throw. What's going on right now (in your example script which I've adapted) is if there's `None` in a column value then readback is incorrect.
  * In `tiledbsoma.io.from_h5ad` and `tiledbsoma.io.from_anndata` we compute an Arrow schema on your behalf based on the Pandas `DataFrame` in your `adata.obs`/`adata.var`
  * Here we set nullability across the board
  * This is not the pathway your script above is using
  * I've verified that `None` in categorical inputs does indeed wend its way down to TileDB null data, and reads back into Arrow/Pandas as intended
* A second issue is whether input Pandas/Arrow data have `pd.Categorical(values=...)` or `pd.Categorical(values=..., categories=...)` (or Arrow or R analog)
  * If you set `categories=["a", "b", "c"]` but all your values are `""`, then we handle this OK
  * It's only when we _auto-compute_ categories, and when all your values are `""`, that you get `Unable to extend an enumeration without a data buffer.`
  * This is a TileDB-SOMA bug.
* A third issue involves nullable booleans
  * Even in the `tiledbsoma.io.from_anndata` case, wherein we do set nullability for TileDB attributes, `None` in these columns is not being handled correctly.
  * I think this is a TileDB-SOMA bug.

As you can see, there is at least a 3-dimensional unit-test matrix to be populated here, as test-driven development, and then worked off until all tests pass.

I'll task out these issues separately and ensure we get this handled correctly in both our Python and R TileDB-SOMA APIs.

**Comment by johnkerl** [comment] 2024-08-07 21:32
See also [[sc-51683]](https://app.shortcut.com/tiledb-inc/story/51683)

**Comment by johnkerl** [comment] 2024-08-08 18:12
@mdylan2 here is a script demonstrating more concretely:

* Using Python (not R)
* Issues with `tiledbsoma.io.from_anndata` / `tiledbsoma.io.from_h5ad` (not `tiledbsoma.Experiment.add_new_dataframe` which you're using)
* Testing out nullables for categorical-of-string, boolean, and integer

I'll task these out separately as discussed.

Next up:

* Do a similar Python writeup for `tiledbsoma.Experiment.add_new_dataframe` -- this is different since there you bring your own schema -- merits similar investigation
* Do a similar survey for R at the analog of `tiledbsoma.io` which includes `from_seurat`
* Do a similar survey for R at the analog of `add_new_dataframe` -- which we have in R -- wherein you, here too, bring your own schema

**Comment by johnkerl** [comment] 2024-08-08 19:25
@mdylan2 I'm going to use #2858 for tracking nullability issues. I believe (please correct me if I'm wrong) the dictinary filter + enumeration attribute question is solved.

Thanks for raising this!

**Comment by mdylan2** [comment] 2024-08-08 19:52
Hi John thanks for all the clarifications! Seems like a more expansive problem than I originally thought.

Yup, dictionary filter + enumeration attribute question is solved. Seems like I just get rid of my Dictionary Filter on categoricals. I'll post my question about nullability on the new thread.

**Comment by johnkerl** [comment] 2024-08-15 21:38
For the case of an enumeration containing only the empty string I've filed [[sc-53027]](https://app.shortcut.com/tiledb-inc/story/53027/users-should-be-able-to-create-an-enumeration-of-which-the-sole-value-is-the-empty-string) with the TileDB Core team.

**Comment by johnkerl** [comment] 2024-08-16 15:19
This is tracked in open issue #2859 -- closing this issue as duplicate.

**Closed** 2024-08-16 15:38 UTC
Labels: bug, blocked
