### ISSUE TITLE
[r] Question about new iterated reader for `SOMASparseNDArray` and `coords`

### ISSUE THREAD

**Issue by mojaveazure** [single-cell-data/TileDB-SOMA#1433] opened 2023-05-30 21:45 UTC
Passing `coords` to `SOMASparseNDArray$read()` (introduced in #1274) has no effect on the resulting object; this is necessary for reading arrays from queries (e.g. #1279)

**Comment by johnkerl** [comment] 2023-05-31 20:35
@mojaveazure given commit https://github.com/single-cell-data/TileDB-SOMA/pull/1279/commits/9dfccc26f112e3d0a91e5e07bb50ee8c7c687dfa -- namely, where you're now using `unname` -- are we certain that `coords` is as non-functional as you believed when you created this issue?

**Comment by mojaveazure** [comment] 2023-05-31 20:53
@johnkerl Yes; the `unname` simply removes the names I was using for easier-to-understand code as `SOMASparseNDArray$read()` freaks out if `coords` is named but the names don't match `SOMASparseNDArray$dimnames()`

If you step into either `query_private$.load_m_axis()` (easy since I left a `browser()` in there 🤦) or `query_private$.load_p_axis()` on a sliced query, you'll find that reading still loads in the full shape, not the slice specified by `coords`

**Comment by pablo-gar** [comment] 2023-06-01 00:50
@mojaveazure have you checked the contents of the matrix? The shape is the same but the values should correspond to the coords you specified, this is also in accordance to the python api. There have been previous discussions on this behavior. 

You are probably looking for a reshaping and likely reindexing functionality of the slices you are specifying. 

Apologies, I’m away from my laptop and can’t test it on my own. 

cc @bkmartinjr for visibility

**Comment by pablo-gar** [comment] 2023-06-01 08:20
Here's the demo, you can see that the size of `sparse@x` changes upon specifying `coords`

```r
library(tiledbsoma)
human_experiment = load_dataset("soma-exp-pbmc-small")                      
x_sparse <- human_experiment$ms$get("RNA")$X$get("data")                                                     
 
# Full Matrix 
sparse <- x_sparse$read()$sparse_matrix()$concat()
length(sparse@x)                   
# [1] 4456                         
                                
# Slice       
obs_ids <- 2:5
var_ids <- 2:5

sparse <- x_sparse$read(coords = list(obs_ids, var_ids))$sparse_matrix()$concat()
length(sparse@x)                                               
# [1] 3
```

And using an "indexer" here is how to reindex and reshape (not sure if this is the most efficient way)

```r
obs_indexer <- setNames(1:length(obs_ids), obs_ids)                                                                                                       
var_indexer <- setNames(1:length(var_ids), var_ids)                                                                                                       
                                                                                                                                                          
sparse_reindexed <- Matrix::sparseMatrix(i=obs_indexer[as.character(sparse@i)],                                                                           
                                          j=var_indexer[as.character(sparse@j)],                                                                          
                                          x=sparse@x,                                                                                                     
                                          dims=c(length(obs_indexer), length(var_indexer)),                                                               
                                          repr="T")                                                                                                       
 
sparse_reindexed 
# 4 x 4 sparse Matrix of class "dgTMatrix"
#                                                                                                                                                         
# [1,] . .        . .                                                                                                                                     
# [2,] . .        . .                                                                                                                                     
# [3,] . 4.074201 . .       
```

**Comment by mojaveazure** [comment] 2023-06-05 16:22
@pablo-gar Then this is the wrong behavior; when `coords` is specified, the resulting matrix should be of that shape

**Comment by pablo-gar** [comment] 2023-06-05 17:05
@mojaveazure this is the correct behavior per the API specification. See what happens in python:

```python
import tiledbsoma             
                            
experiment = tiledbsoma.open("apis/python/notebooks/data/sparse/pbmc3k")    
sparse = experiment.ms["RNA"].X["data"].read(coords = [range(5), range(5)]).coos().concat()    
                                                                                                            
sparse.non_zero_length  
# 25

sparse.shape
# (9223372036854773760, 9223372036854773760)
```

To have the behavior you are specifying there are 3 options I can see moving forward:

1. You implement the re-indexing/re-shaping behavior **where need it** as in my comment above (this is what is done in `from_anndata` in the python API).
2. We provide a **high-level  general-purpose API function** to re-index/re-shape.
3. We **change the default behavior of `read()`** in the API specification -- this option is the least trivial and needs a longer discussion, some of which have happened and landed on the current behavior.
4. Other option(s) I may not bee seeing at the moment.

**Comment by pablo-gar** [comment] 2023-06-05 19:00
@mojaveazure  yeah the SOMA spec is a bit (intentionally?) vague on that point, the discussions on that were around the implementation of it. The methods `.read().coos()`/`$read()$spase_matrix()` _do_ only get arrays of data with the specified `coords` -- the are no arrays that are materialized beyond the specified `coords`. This `coords` functionality also is quite literal in the indexing sense, e.g. if you get a slices with `coords=[100,101,103]` you can access them in the slice with those exact same indexes. 

Now, I do agree that most end-users want a re-indexed/re-shaped version of slices but that removes some low-level capabilities for out-of-core operations, which is why I lean towards option 2.

Most of the discussions and decisions on this happened before my time on tiledbsoma and I (and others at CZI) faced the same confusion in the past with Python and had some conversations with @bkmartinjr about it, so it would be good to bring this up again with the full team.

@johnkerl Do you have any recommendations to bring visibility to Paul's request?

**Comment by johnkerl** [comment] 2023-06-21 15:20
This is a duplicate of #1445

**Comment by pablo-gar** [comment] 2023-06-21 20:03
@mojaveazure please close this issue when you complete the seurat and bioconductor work

**Comment by pablo-gar** [comment] 2023-08-28 22:32
Completed

**Closed by pablo-gar** 2023-08-28 22:32 UTC
Labels: needs-discussion, python-api, r-api, blocker
