### ISSUE TITLE
[Bug]Failed to build on Windows

### ISSUE THREAD

**Issue by shibbit** [single-cell-data/TileDB-SOMA#3187] opened 2024-10-17 09:18 UTC
**Description**
I tried to build the project on Windows and the following errors occured:

```
Building wheels for collected packages: tiledbsoma
  Building editable for tiledbsoma (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for tiledbsoma (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      Not in the expected path relative to Git root: apis\python\version.py != apis/python/version.py
      running editable_wheel
      creating C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info
      writing C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\PKG-INFO
      writing dependency_links to C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\dependency_links.txt
      writing requirements to C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\requires.txt
      writing top-level names to C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\top_level.txt
      writing manifest file 'C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'py.typed'
      no previously-included directories found matching 'dist_links\libtiledbsoma\test\__pycache__'
      writing manifest file 'C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma.egg-info\SOURCES.txt'
      creating 'C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma-2024.10.17.dev2168309754.dist-info'
      C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py:115: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      creating C:\Users\guote\AppData\Local\Temp\pip-wheel-93cjep34\.tmp-rt8t64hd\tiledbsoma-2024.10.17.dev2168309754.dist-info\WHEEL
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 138, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 341, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 264, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 291, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\dist.py", line 991, in run_command
          super().run_command(command)
        File "C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 218, in run
        File "<string>", line 186, in find_or_build_package_data
        File "C:\Users\guote\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\guote\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\guote\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      C:\Users\guote\AppData\Local\Temp\pip-build-env-ob9sh8r1\overlay\Lib\site-packages\setuptools\_distutils\dist.py:973: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `tiledbsoma` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      Checking: C:\Users\guote\Desktop\Projects\TileDB-SOMA\apis\python\dist_links\dist\lib\tiledbsoma.dll exists: False
      Checking: C:\Users\guote\Desktop\Projects\TileDB-SOMA\apis\python\dist_links\dist\bin\tiledbsoma.dll exists: False
      Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for tiledbsoma
Failed to build tiledbsoma
ERROR: Could not build wheels for tiledbsoma, which is required to install pyproject.toml-based projects
```

**To Reproduce**
I followed the instructions to install both from cloned source code **pip install -v -e** and directly from pip source **pip install tiledbsoma**

**Versions :**
 - TileDB-SOMA version: latest version
 - Language and language version: python 3.9.0
 - OS (e.g. MacOS, Ubuntu Linux): Windows

**Additional context**
I tried install tiledbsoma on a new clean conda environment which contains no libraries not even Python, but the same errors still occur, it says can't find tiledbsoma.dll in dist_links\dist\bin\tiledbsoma.dll, I looked it up on this repository, there is also no this file, so I assume maybe tiledbsoma does not support windows at the current moment?

**Comment by johnkerl** [comment] 2024-10-17 12:39
@shibbit TileDB-SOMA on Windows is not supported at the present time. Please also see #2631.

**Comment by johnkerl** [comment] 2024-11-19 16:53
Duplicate of #2631.

**Closed by johnkerl** 2024-11-19 16:53 UTC
