### ISSUE TITLE
[r/c++] Add R support for C++ reindexer

### ISSUE THREAD

**Issue by beroy** [single-cell-data/TileDB-SOMA#1819] opened 2023-10-24 03:01 UTC
Rcpp integration for the fast reindexer is needed if it is required to be used by R.

Executive summary of the use-case:

* Experiment is 60M cells x 60K genes
* Someone queries for `cell_type == "liver"`
* Answer comes back with rows 493, 5527, 34567, .......
* Reindexing is the renumbering of obs row and X row (and/or var row and X column) to be 0,1,2,...
* We made this faster for Python/C++ using threads
* That needs to be ported to R

PRs: #1728, #2061, #2081, #2098

**Comment by eddelbuettel** [comment] 2023-10-24 03:08
That tends to be entirely on the client side:

```r
> Rcpp::cppFunction("double mysum(std::vector<double> v) { double s = 0; for (size_t i=0; i<v.size(); i++) { s+=v[i]; } return(s); }")
> mysum(1:5)
[1] 15
> 
```

As discussed, the C++ is 'Switzerland'. No Python bindings. No R bindings. Just clean C++ code.  The API side will take care of the rest.

**Comment by johnkerl** [comment] 2024-02-12 22:19
As noted on #1853 my current understanding is we should do #1853 before this issue

**Comment by eddelbuettel** [comment] 2024-02-12 22:46
Agreed, and that was also the consensus on the last two or so Friday calls.

**Comment by eddelbuettel** [comment] 2024-03-04 13:39
Duplicate of #1610

**Closed** 2024-03-04 14:17 UTC
Labels: r-python-parity
