### ISSUE TITLE
Python tiledbsoma: package needs explicit error/exception protocol, per-operation docs

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#328] opened 2022-09-23 15:44 UTC
It would be nice if there was an set of exception classes defined to cover common errors, and if the Python API was better about throwing meaningful exceptions (ie, actionable) rather than simply asserting.  In an ideal world, common cases would not throw storage-engine specific exceptions.

Suggest that we start this with the API refinement pass

**Comment by johnkerl** [comment] 2022-09-23 15:48
In my work building systems in various languages over various decades (C++, Java, Go, etc.), i think there are three main ways for handling it -- say our system is `Foo` and it has various library/package dependencies:

One: have `Foo` exceptions be simple and generic -- `assert(...)` and raise `Exception(...)`:
```
try:
    return somelib.somefunc(...)
except somelib.SpecificException as e:
    raise Exception(...) from e
```

Two: have a single `FooException` class which wraps everything, with `from` to track the caused-by:
```
try:
    return somelib.somefunc(...)
except somelib.SpecificException as e:
    raise FooException(...) from e
```

Three: have multiple child classes of `FooException` classes like `FooIOException`, `FooArgumentException`, whatever:

```
try:
    return somelib.somefunc(...)
except somelib.SpecificException as e:
    raise FooIOException(...) from e
except somelib.OtherSpecificException as e:
    raise FooArgumentException(...) from e
```

Of course, here `Foo` is `TileDBSOMA`.

I've done all three over the years and they all have their merits -- the first one is OK at first and is probably best for simple systems but we've probably already outgrown it.

I lean more toward the second than the third but can go either way.

Note even in the third case, `FooIOException` et al. should inherit from the base class `FooException` so there is room to ramify later -- a clear 'growth path' from mode two to mode three.

**Comment by johnkerl** [comment] 2022-09-23 15:49
@thetorpedodog thoughts? This is something I'd love you to work on if you're interested -- sequencing-wise this is definitely after class-wide API-design work (which is immediate term) but before alpha release ...

**Comment by bkmartinjr** [comment] 2022-10-14 17:17
The code contains a start at a SOMAError class, with some inconsistent usage of that class.

**Comment by johnkerl** [comment] 2023-01-04 05:40
Duplicate of #433

**Closed by johnkerl** 2023-01-04 05:40 UTC
Labels: python-api
