### ISSUE TITLE
[Bug] C++ `nnz` incorrectly warning about unconsolidated array when the array has one fragment

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#971] opened 2023-02-20 17:07 UTC
**Describe the bug**

When I open the consolidated `obs` array in the cell census, and call `count` on the DataFrame, I get the incorrect warning:
> [2023-02-20 17:00:11.416] [tiledbsoma] [Process: 17243] [Thread: 17243] [warning] [SOMAReader] nnz() found consolidated or overlapping fragments, counting cells...

The array _is_ consolidated:
```
In [6]: tiledb.array_fragments(human.obs.uri)
Out[6]: 
{'array_schema_name': ('__1676327457738_1676327457738_20f857d1f9294eac8e12d1ddedab3c31',),
 'array_uri': 's3://cellxgene-data-public/cell-census/2023-02-13/soma/census_data/homo_sapiens/obs',
 'cell_num': (43743262,),
 'has_consolidated_metadata': (False,),
 'nonempty_domain': (((0, 43743261),),),
 'sparse': (True,),
 'timestamp_range': ((1676327460288, 1676328660764),),
 'to_vacuum': (),
 'unconsolidated_metadata_num': 1,
 'uri': ('s3://cellxgene-data-public/cell-census/2023-02-13/soma/census_data/homo_sapiens/obs/__fragments/__1676327460288_1676328660764_2dd428eafc1741b08ccf54b34ab07d02_17',),
 'version': (17,)}
```

**To Reproduce**

*Note* this URI points to a bucket in us-west-2, so set the AWS_REGION environment variable to that value.

```python
import tiledb
import tiledbsoma as soma
obs = soma.open('s3://cellxgene-data-public/cell-census/2023-02-13/soma/census_data/homo_sapiens/obs')
print('count', obs.count)
print('fragments', len(tiledb.array_fragments('s3://cellxgene-data-public/cell-census/2023-02-13/soma/census_data/homo_sapiens/obs')))
```

for me, this produces:
```
[2023-02-20 17:06:33.480] [tiledbsoma] [Process: 17243] [Thread: 17243] [warning] [SOMAReader] nnz() found consolidated or overlapping fragments, counting cells...
count 43743262
fragments 1
```

**Versions (please complete the following information):**

```
In [13]: soma.show_package_versions()
tiledbsoma.__version__    0.5.0a11
tiledb.__version__        0.20.0
core version              2.14.0
python version            3.9.16.final.0
```

**Comment by johnkerl** [comment] 2023-02-21 16:03
This is a duplicate of #930

**Comment by bkmartinjr** [comment] 2023-02-21 16:12
> This is a duplicate of https://github.com/single-cell-data/TileDB-SOMA/issues/930

Can you elaborate?  One bug is a performance regression (per the title), and the other is an incorrect warning about fragment count or overlap.  As a naive reader, the content of the two issues appears to be different.

If you could add additional info showing how they are the same, that would be great.

**Comment by johnkerl** [comment] 2023-02-21 16:47
@bkmartinjr we get the warning when we fall back to the slow method

Line numbers were shown on #930 

> This is triggered from
https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/libtiledbsoma/src/soma_reader.cc#L214-L218

is where we call `nnz_slow` and

https://github.com/single-cell-data/TileDB-SOMA/blob/0.5.0a11/libtiledbsoma/src/soma_reader.cc#L283-L285

is where the "counting cells" log-line is being printed

**Comment by johnkerl** [comment] 2023-02-21 16:49
I've added the second link just above to #930

**Comment by bkmartinjr** [comment] 2023-02-21 16:50
Ah, I did not see any indication of this being tied to the fragment count error in your issue.  

Feel free to consolidate, but I think that the fragment count is being incorrectly determined is a clue worth retaining.

**Comment by johnkerl** [comment] 2023-02-21 17:07
Yes @bkmartinjr it is absolutely a clue worth retaining -- we are very much on the same page

**Closed** 2023-02-21 17:08 UTC
