### ISSUE TITLE
Multi-lingual API synchronization work

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#385] opened 2022-10-07 19:06 UTC
To keep R & Python in sync (both API & implementation interoperability), propose several workstreams:
1. Multi-lingual/implementation unit tests
    * 4 steps in R/Python unit-test code: R tests itself; Python tests itself; Python writes data then R reads and asserts; vice versa
2. ABC for both, and do multilingual code review on ABCs
3. Round-tripping data between the different implementations

**Comment by johnkerl** [comment] 2023-01-08 00:45
Perhaps superseded by #643

**Comment by maniarathi** [comment] 2023-02-02 17:34
Dupe of #839

**Closed by maniarathi** 2023-02-02 17:34 UTC
